version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: amlops-postgres
    environment:
      POSTGRES_DB: amlops
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - amlops_pg_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: amlops-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniopassword
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - amlops_minio_data:/data

volumes:
  amlops_pg_data:
  amlops_minio_data:
